spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: '{cipher}AQBGjpdeeVKtj2aei5kq/3yPBUvzhl7DOiwSX+glmEg30si2gp0X1AUVmerFf4Qx70VPcv0p1WqIhVPJt4C3OaOZ+lIzfqthvdQgMD3nxWga9bdWZK5EgYUats0iPFb+KDkplcLwrM/0z3za7YN6ZjmS5eRvm+jw3q2nX1Q/mga2ohjmYxvX09tk28Orhcse97KHpYIShc+LBuFtQnW8ZvUnGxjRgvHNTKM4WFwyzaaycKevPEKy3ROghYlkwaZjkzuSdYYJ4z+bO5QrlmlhPLJzEN2T5vqUNrtQjgSOYkpBo9cXWAfN+mMnM3d32Anx8ZTIwD1QbesGYyfhlE1VKDPwIGHXh+3wqG9BIjgJLvjUnmtAJ+lHjcU9aNwQ3ne0voY='
    password: 

token:
  expiration_time: 864000000
  secret: '{cipher}AQCljaaBo0Xoj9o1lDDlZ++Ua7s7NU7/ZAk+0vgdClFIO1Yxbofo0m51BM71/yRxdyjfRyvXe3aJtub9bwgkddgMISMeqxRVGFhVEr+XD0NO8VlyNm8X10UwDvV0hTkdM91U6Mg8yL6phUaQwkGABz88Nl359w4uY1Eg8jvN4g2RDHwUxxO8okE/Qwy5n19UpncUVLlyO3pEK1eNEDdcDuqd+VUjEt8V4k+6tNQpy9I2ymnt6NeiQtI6L7K+qd/1HS1qsZHa9bH/sQsOjKXfsaaDonpu8do+3ZPm981zUhXm/929jdejZy3ZEylu6DtLpRJT34YaXmnTiNtDPV/Q4+Qa0jxl7F3iK78dGZKtZY3RyRJ2TLJtdOgv5dlL1KeFtbI='
